### ISSUE TITLE
Replace radare-bindings with r2pipe

### ISSUE THREAD

**Issue by fabsx00** [octopus-platform/bjoern#2]
We can spare the user from the hassle of having to compile radare bindings by using r2pipe instead. With r2pipe, we simply communicate with an r2-instance via a pipe via `r_core_cmd_str()`.

See https://github.com/radare/radare2-bindings/tree/master/r2pipe and 
https://github.com/radare/radare2-bindings/blob/master/r2pipe/java/org/radare/r2pipe/R2Pipe.java

**Comment by Maijin** [comment]
:+1:
